services:
  - mongodb
language: python
python:
  - 2.7
  - 3.3
  - 3.4
install:
  - pip install -r pip_requirements.txt
script:
  - py.test --cov-report term-missing --cov TestSheriff
after_success:
  - coveralls
